### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by sankarganesh1098** [manjeshpv/node-oauth2-server-implementation#4] opened 2016-09-12 13:12 UTC
{"message":"Server error: missing client `grants`","code":503,"name":"server_error"}

**Comment by sheershoff** [comment] 2016-09-13 06:09
1. what request do you use?
2. do you use the postman examples collection?
3. as far as I can see it's when you do not use Authentication header, which should always be used when addressing oauth exposed methods.

**Comment by mwohlert** [comment] 2016-09-20 08:29
I am facing the same problem.
1. Authorize
2. yes
3. I think the problem is due to the use of mongoose here:
   https://github.com/manjeshpv/node-oauth2-server-implementation/blob/master/components/oauth/mongo-models.js#L44

Since mongoose returns a mongoose Object it is not modifiable. I think .findOne(options).lean().then should be used. 

But since I am basically a OAuth2.0 noob I can be totally wrong.

**Comment by chenzhizhuan** [comment] 2016-10-11 08:50
Me too, set db:'sql' run is ok, but set db:'mongo' run is throw an error: "{"message":"Server error: missing client `grants`","code":503,"name":"server_error"}". 
Looks like is mongodb findOne not work.

**Comment by MrHzAkI** [comment] 2017-01-06 10:49
Same problem here!

**Comment by evolvingfunctions** [comment] 2017-01-27 07:07
You are on the right track. The error happens when grant object was not found or returned when the oauthClients collection is queried. Confirm your model contains a grants array similar to this:

```
{
    "clientId": "foo",
    "clientSecret": "bar ",
    "redirectUri": "/yourOauthRedirectUri",
    "grants": [
        "password",
        "authorization_code",
        "refresh_token"
    ]
}
```

**Comment by rnl2004** [comment] 2017-04-13 14:01
Hi, I have the same error. 
"OAuthClient": {
      "id": 1,
      "name": null,
      "client_id": "democlient",
      "client_secret": "democlientsecret",
      "redirect_uri": "http://localhost/cb",
      "grant_types": "password",
      "scope": "",
      "user_id": 1
    }

Is this the one you've mentioned?
 "grant_types": "password",
What will be the expected returned of that grant_types element is array of grant_types? When i check it's just a string.

**Comment by rnl2004** [comment] 2017-04-13 14:12
What are the possible values of grant_types field in table "oauth_clients". thanks

**Comment by rnl2004** [comment] 2017-04-18 03:24
Hi manjeshpv, Good day!

I have encountered an issue on creating new access token:
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Cache-Control:
no-cache" -H "Postman-Token: c3df2fab-440f-09e4-0c5c-c9f46ef9836b" -d "username=admin&password=admin
&grant_type=password&client_id=democlient&client_secret=democlientsecret" "http://localhost:3000/oauth/token"
{"message":"user is not defined","code":503,"name":"server_error","inner":{}}

I already updated the node-oauth2-server-implementaion repo on my local machine. I'm using mysql oauth_demo schema as is. Did i missed something? Thanks

**Comment by rnl2004** [comment] 2017-04-30 03:04
Hey guys! Have you encountered this error?
$ curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Cache-Control: no-cache" -H "Postman-Token: c3df2fab-440f-09e4-0c5c-c9f46ef9836b" -d "username=admin&password=admin&grant_type=password&client_id=democlient&client_secret=democlientsecret" "http://localhost:3000/oauth/token"
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 178 100 77 100 101 5133 6733 --:--:-- --:--:-- --:--:-- 6733{"message":"user is not defined","code":503,"name":"server_error","inner":{}}

I already updated my repo and mySQL db also but got this error.

**Comment by egachi** [comment] 2017-05-05 03:07
Hi, I'm getting the same error with MongoDB implementation:

```
{
  "statusCode": 503,
  "status": 503,
  "code": 503,
  "message": "user is not defined",
  "name": "server_error",
  "inner": {}
}
```

Any idea? I have double checked and the user exists in db collection.

**Comment by rnl2004** [comment] 2017-05-05 04:49
Still waiting a feedback from the author,  and i am not sure if the source code fully committed maybe they still working on it. Any updates on this?

**Comment by manjeshpv** [comment] 2017-05-05 05:51
You can check the above commit as of now.

**Closed as completed** 2017-05-05 05:51 UTC

**Comment by rnl2004** [comment] 2017-05-05 11:55
Hi manjeshpv, when i check the code, is this fix only uses mongodb? How about mySQL it's work when i invoked the end-point. Please verify thanks.

**Comment by rnl2004** [comment] 2017-05-05 12:11
I appreciated your fixes in mongoDB it seems to work, but hopefully there were also a fix for mySQL database.

The output when i used mongodb else got error on mySQL:
{  
   "client":{  
      "_id":"590c6a7c23a54201484c3d19",
      "client_id":"democlient",
      "client_secret":"democlientsecret",
      "redirect_uri":"http://localhost/cb",
      "User":"590c6a7b23a54201484c3d12",
      "__v":0
   },
   "user":{  
      "_id":"590c6a7b23a54201484c3d12",
      "username":"admin",
      "password":"admin",
      "__v":0
   },
   "access_token":"b1185aeefc3c16004bb9c06d0f3f33ce03e0be87",
   "refresh_token":"29cd6e2404c08b1a634bbb460cbd5e53b3dd1521",
   "accessToken":"b1185aeefc3c16004bb9c06d0f3f33ce03e0be87",
   "accessTokenExpiresAt":"2017-05-05T13:05:40.695Z",
   "refreshToken":"29cd6e2404c08b1a634bbb460cbd5e53b3dd1521",
   "refreshTokenExpiresAt":"2017-05-19T12:05:40.696Z"
}

**Comment by rnl2004** [comment] 2017-05-05 12:35
Just want to share. I have a simple fixed on uses mysql db, just simply copy the implementation code in mongo models and it works! But no guarantee this fix the issue :(. Possible other function will not work. Thank you manjeshpv.

**Comment by manjeshpv** [comment] 2017-05-05 16:26
please update error with mysql, and clone repo fresh again

**Comment by Jorger** [comment] 2017-05-10 18:58
Hello, I have the same problem.

![test_oath_02](https://cloud.githubusercontent.com/assets/30050/25915845/5d74c6ca-3588-11e7-9bdd-546e95556532.gif)

In this case I connect with Mysql.

It is posible connect with LDAP with this library?

Thanks so much.

Jorge,

**Comment by rnl2004** [comment] 2017-05-10 22:07
Jorger, please tried to add client_id and user_id foreign key value one of the table manually. Because, the oauth_demo.sql script has missing id's reference to the client and user. The create sequelize associated with that table seem not working in mysql db not sure if the issue from the associated tables. I am not familiar yet in sequelize need to learn more.

**Comment by rahul-soshte** [comment] 2019-12-18 14:53
Also the issue can be you must have not set seedMongoDB: true or seedDB: true in the config.js file, depending on which database you are using. I did that and issue got resolved.

**Comment by Rayan20** [comment] 2020-05-31 17:28
I have the same issue Server error: missing client `grants` when using redis. Any solution to this issue?

**Comment by shubham-mohit** [comment] 2023-12-06 11:33
{
    "statusCode": 500,
    "status": 500,
    "code": 500,
    "message": "Missing parameter: `headers`",
    "name": "invalid_argument"
} I got this error for /authorise endpoint
